name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send deploy request
        run: curl -X POST -H "Content-Type application/json" 
                  -d '{"secretKey":"${{ secrets.SECRET_KEY}}"}' 
                  http://vesper.host:3000/deploy
